name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load web-handout/quartz/.node-version
        id: node-version
        run: echo "::set-output name=node-version::$(cat web-handout/quartz/.node-version)"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build code snippets
        run: ./web-handout/py2md.sh codes/ web-handout/quartz/content/codes/

      - name: Build Quartz site
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        id: upload
        with:
          path: public

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4